# .github/workflows/test.yml
name: Test Fogo

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    container:
      image: fogo
    steps:
      - uses: actions/checkout@v3
      - name: Run tests
        run: pytest